pipeline {
    agent any

    environment {
        IMAGE_NAME = 'plini0/webapp'
        REGISTRY_CREDENTIALS = 'docker-hub-creds'
        BUILD_CONTEXT = 'Delivery_esercizio_1'
    }

    stages {
        stage('Clone') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:latest", "${BUILD_CONTEXT}")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', REGISTRY_CREDENTIALS) {
                        docker.image("${IMAGE_NAME}:latest").push()
                    }
                }
            }
        }
    }
}
